---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvwa-mysql-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
