---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-mysql
  labels:
    app: dvwa
    tier: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: dvwa
    tier: mysql

