---
apiVersion: v1
kind: Service
metadata:
  name: dvwa
  labels:
    app: dvwa
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: dvwa
    tier: frontend

